force-app/main/default/objects/Test_Status__c/Test_Status__c.object-meta.xml
<CustomObject>
    <label>Test Status</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Test Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needed</fullName>
                <default>true</default>
                <label>Needed</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Passed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Status__c/fields/Work_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Work Item</label>
    <referenceTo>sf_devops__Work_Item__c</referenceTo>
    <relationshipLabel>Test Statuses</relationshipLabel>
    <relationshipName>Test_Statuses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/preApproval/TestStatusApprovalValidator.cls
/**
 * Verify the latest Test_Status for this work item is Passed.
 */
global with sharing class TestStatusApprovalValidator extends sf_devops.PreApprovalValidator {

    global override sf_devops.SpiPreApprovalValidationResponse validate(
        sf_devops.SpiPreApprovalContext context
    ) {
        List<Test_Status__c> statuses = [SELECT Status__c FROM Test_Status__c WHERE Work_Item__c = :context.getWorkItemId() ORDER BY CREATEDDATE DESC LIMIT 1];
        if (statuses.size() == 0){
            return sf_devops.SpiPreApprovalValidationResponse.fail('Missing QA', 'This work item does not have a status');
        }
        else if (statuses[0].Status__c != 'Passed'){
            return sf_devops.SpiPreApprovalValidationResponse.fail('Failed QA', 'Please complete QA on this work item.  See the <a target="_blank" href="/' + 
            statuses[0].Id + '">QA Record</a>');
        }
        return sf_devops.SpiPreApprovalValidationResponse.pass();
    }

}